vich_uploader:
    db_driver: orm

    mappings:
       imageMarches:
           uri_prefix: /images/imageMarches
           upload_destination: '%kernel.project_dir%/public/images/imageMarches'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true